RedditC/RClone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls')),
    url(r'^post/', include('posts.urls')),
    url(r'^$', views.home, name="home")

]

RedditC/accounts/urls.py
from django.conf.urls import url
import accounts.views

app_name = 'accounts'
urlpatterns = [
	url(r'^signup/', accounts.views.signup, name = 'sign_up'),
    url(r'^login/', accounts.views.login, name = 'log_in'),
    url(r'^logout/', accounts.views.logout_view, name = 'log_out'),

]

RedditC/posts/urls.py
from django.conf.urls import url
import posts.views

app_name = 'posts'
urlpatterns = [
	url(r'^create/', posts.views.create, name = 'create'),
	url(r'(?P<pk>[0-9]+)/upvote', posts.views.upvote, name = 'upvote'),
	url(r'(?P<pk>[0-9]+)/downvote', posts.views.downvote, name = 'downvote'),
	url(r'^user/(?P<fk>[0-9]+)', posts.views.userposts, name='userposts'),

]

RedditC/accounts/models.py
from django.db import models

# Create your models here.

RedditC/posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	tittle = models.CharField(max_length=100)
	url = models.CharField(max_length=500)
	pub_date = models.DateField()
	author = models.ForeignKey(User, default="")
	votes_total = models.IntegerField(default=1)

	def __str__(self):
		return self.tittle

RedditC/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout


def signup(request):
	if request.method == "POST":
		if request.POST["password"] == request.POST["password1"]:
			try:
				user = User.objects.get(username = request.POST["username"])
				return render(request,'accounts/new_account.html', {'message': "Username has already been taken"})
			except User.DoesNotExist:
				User.objects.create_user(username = request.POST["username"], password = request.POST["password"])
				return redirect('home')
		else:
			return render(request,'accounts/new_account.html', {'message': "Passwords didn't match"})
	else:
			return render(request,'accounts/new_account.html')

def login(request):
	if request.method == "POST":
		username1 = request.POST["username"]
		passwd = request.POST["password"]
		user = authenticate(username = username1, password = passwd)
		if user is not None:
			auth_login(request, user)
			if request.POST.get('next') is not None:
				return redirect(request.POST['next'])
			return redirect('home')
		else:
			return render(request, 'accounts/login.html', {'message':"Invalid Username or Password"})
	else:
		return render(request, 'accounts/login.html')

def logout_view(request):
    if request.POST:
    	logout(request)
    	return redirect('home')

RedditC/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post
from django.contrib.auth.models import User
from django.utils import timezone

@login_required(login_url = '/account/login/')
def create(request):
	if request.POST:
		if request.POST['tittle'] and request.POST['url']:
			url = request.POST['url']
			if url.startswith('http://') or url.startswith('https://'):
				pass
			else:
				url = 'http://' + url
			post = Post(tittle=request.POST['tittle'],
				url=url,
				pub_date=timezone.datetime.now(),
				author=request.user)
			post.save()
			return redirect('home')

		else:
			return render(request, 'posts/create.html', {'message': 'You must provide a tittle and url'})
	return render(request, 'posts/create.html')

def home(request):
	recent_posts = Post.objects.order_by('-votes_total')
	return render(request, 'posts/home.html', {'recent_posts':recent_posts})

def upvote(request, pk):
	if request.POST:
		post = Post.objects.get(id = pk)
		post.votes_total += 1
		post.save()
	return redirect('home')

def downvote(request, pk):
	if request.POST:
		post = Post.objects.get(id = pk)
		post.votes_total -= 1
		post.save()
	return redirect('home')

def userposts(request, fk):
    posts = Post.objects.filter(author__id=fk).order_by('-votes_total')
    author = User.objects.get(pk=fk)
    return render(request, 'posts/userposts.html', {'posts':posts, 'author':author})

RedditC/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
	{% if message %}
		{{ message }}
	{% endif %}
	<h1>Log in!</h1>
	<form method="POST" action={% url 'accounts:log_in' %}>
		{% csrf_token %}
		{% if request.GET.next %}
		<input type="hidden" name="next" value={{ request.GET.next }}>
		{% endif %}
		<span>Username:</span>
		<br>
		<input type="text" name="username">
		<br>
		<span>Password</span>
		<br>
		<input type="password" name="password">
		<br>
		<br>
		<input class="btn btn-primary" type="submit" value="Log in!">
	</form>
{% endblock %}

RedditC/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
	<h1>You are out</h1>
{% endblock %}

RedditC/accounts/templates/accounts/new_account.html
{% extends 'base.html' %}
{% block content %}
	{% if message %}
		{{ message }}
	{% endif %}
	<h1>Sing up!</h1>
	<form method="POST" action={% url 'accounts:sign_up' %}>
		{% csrf_token %}
		<span>Username:</span>
		<br>
		<input type="text" name="username">
		<br>
		<span>Password</span>
		<br>
		<input type="password" name="password">
		<br>
		<span>Confirm your password</span>
		<br>
		<input type="password" name="password1">
		<br>
		<br>
		<input class="btn btn-primary" type="submit" value="Sing up!">
	</form>
{% endblock %}

RedditC/posts/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}
	{% if message %}
		{{message}}
	{% endif %}
	<h1>Creating new Post</h1>
	<form method="POST" action={% url 'posts:create' %}>
		{% csrf_token %} 
		<input type="hidden" name="id" value="{{ user.id }}" />
		<span>Tittle</span>
		<br>
		<input type="text" name="tittle">
		<br>
		<span>URL</span>
		<br>
		<input type="text" name="url">
		<br>
		<br>
		<input class="btn btn-primary" type="submit" value="Post it!">
	</form>
{% endblock %}

RedditC/posts/templates/posts/home.html
{% extends 'base.html' %}
{% block content %}
	<h1>Home page</h1>
	<a href="{% url 'posts:create' %}">New post</a>
	<br>
	{% if recent_posts %}
		{% for post in recent_posts.all %}
		<table>
 			 <tr>
				<td style="padding-right: 20px;">
					<a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()">
						<span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span>
					</a>
					<br/>
					{{ post.votes_total }}<br/>
					<a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()">
						<span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
					</a>
				</td>
			    <td>
			    <a target="_blank" href="{{ post.url }}">{{ post.tittle }}</a><br/>{{ post.pub_date_pretty }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a></td>
			  </tr>
</table>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
  {% csrf_token %}
  <input type="hidden">
</form>

<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
 {% csrf_token %}
 <input type="hidden">
 </form>

		{% endfor %}
	{% endif %}
{% endblock %}

RedditC/posts/templates/posts/userposts.html
{% extends 'base.html' %}

{% block content %}
	<h1>All Posts by {{ author.username }}</h1>
	<br/>

	{% for post in posts.all %}

	<table>
	  <tr>
	    <td style="padding-right: 20px;">
	    	<a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()">
	    	<span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span>
	    	</a>
	    	<br/>{{ post.votes_total }}<br/>
	    	<a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()">
	    	<span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
	    	</a>
	    </td>
	    <td>
	    	<a target="_blank" href="{{ post.url }}">{{ post.tittle }}</a>
	    	<br/>{{ post.pub_date_pretty }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a>
	    	</td>
	  </tr>
	</table>

	<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
	  {% csrf_token %}
	  <input type="hidden">
	</form>

	<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
	 {% csrf_token %}
	 <input type="hidden">
	 </form>

	{% endfor %}

{% endblock %}

RedditC/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>RClone</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">RClone</a>
        </div>
        <div class="collapse navbar-collapse" id="mynav">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
           	<li><a href="#" onClick="document.getElementById('logout').submit()">Logout</a></li> 
            <form id="logout" method="POST" action="{% url 'accounts:log_out' %}">
              {% csrf_token %}
              <input type="hidden">
            </form>
            {% else %}
            <li><a href="{% url 'accounts:sign_up' %}">Signup</a></li>
            <li><a href="{% url 'accounts:log_in' %}">Login</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>